x-veld:
  code:
    description: "This code veld encapsulates a publishing workflow to pypi.org . It uses 
      setuptools and a template python module can be found at ./data/test_python_module/"
    topic:
      - pypi
      - packaging


    inputs:
      volume: /veld/input/
      content: "python code base"
      description: "Any suitable python code base containing a setup.py or pyproject.toml ."

    config:
      - environment_var: TWINE_USERNAME
        description: "Contains the username, or better, just `__token__` if a token is used which 
          was created on pypi.org ."
        default: "__token__"
        var_type: str
      - environment_var: TWINE_PASSWORD
        description: "Contains the password, or better, a token which was created on pypi.org .

          IMPORTANT: DON'T HARDCODE THE TOKEN HERE!
         
          Rather define this environment variable on the host, by either:
          - PREFERRED: do this manually before calling this docker compose service. On linux and 
            mac, this can be done with `export TWINE_PASSWORD=<TOKEN>` and on windows with 
            `set TWINE_PASSWORD=<TOKEN>` (and the same way for `TWINE_USERNAME`) before launching 
            a docker compose service.
          - LESS PREFERRED: only do this if you know .gitignore: you may persist it in a `.env` 
            file (with the content simply being `hf_token=<TOKEN>`) file next to the chain 
            veld yaml file, which docker would automatically load, and then add the `.env` to 
            `.gitignore`!"
        var_type: "str"
      - environment_var: testing
        description: "If set to true, it will publish to test.pypi.org . If set to false, it will 
          publish to pypi.org ."
        var_type: bool

services:
  veld_publish:
    build: .
    volumes:
      - ./veld_publish.sh:/veld/code/veld_publish.sh
      - ./data/test_python_module/:/veld/input/
    command: bash /veld/code/veld_publish.sh
    working_dir: /veld/input/
    environment:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD:
      testing: true

